# only used for local

version: latest

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped


networks:
  internal-app-network:
    external: true
