version: latest

services:
  angular-app:
    build: .
    container_name: angular-app
    ports:
      - '4200:4200'
    volumes:
      - ./:/angular-app
      
networks:
  internal-app-network:
    external: true